Added ChatSDK & more complete binding for all libraries
Softeq/Zendesk-xamarin-ios pull request #10
Opened 2022-08-18 08:38 UTC by thisisthekap

Fixes #8 and #9

2022-09-06 04:51 UTC, thisisthekap commented
@wcoder @TimofeyBurak @sleushunou @vadimpylsky Whom should I reach out to to get this PR reviewed & merged?

2022-09-06 08:58 UTC, wcoder commented
/azp run

2022-09-20 13:47 UTC, thisisthekap commented
@wcoder @TimofeyBurak @sleushunou @vadimpylsky Are you able to provide me with the log files of the failed CI build?

2022-09-21 09:45 UTC, wcoder commented
@thisisthekap The review is in progress and takes a lot of time. Thank you for waiting.

Could you please sync with the latest master branch to fix CI check?

2022-09-21 09:47 UTC, thisisthekap commented
@wcoder Did the merge.

2022-10-06 22:28 UTC, wcoder requested changes
Bindings work well for Chat SDK ~but don't work for Support SDK~:

~Basic `ZDKHelpCenterUi.BuildHelpCenterOverviewUi()` returns null.~
~Some classes can' t be load, for example:~
> ~System.Exception: Could not create an native instance of the type 'ZendeskCoreSDK.Bindings.ZDKObjCJwt': the native class hasn't been loaded.~

Please try these examples:
```cs
UIViewController requestList = ZDKRequestUi.BuildRequestUiWith(new NSObject[]{});
            
UIViewController helpCenter = ZDKHelpCenterUi.BuildHelpCenterOverviewUiWithConfigs(new ZDKConfiguration[]{});
            
UIViewController helpCenter = ZDKHelpCenterUi.BuildHelpCenterOverviewUi();
            
PresentModalViewController(helpCenter, true);
```

Support SDK also works fine. It was local issues with Rider and MSBuild caches.

2022-10-06 22:28 UTC, yauhenipakala commented on nuget/Softeq.ZendeskCommonUISDK.iOS.nuspec
> +                <dependency id="Softeq.ZendeskSDKConfigurationsSDK.iOS" version="1.1.11.4" />
Why is this package required as a dependency?
As I see native [CommonUISDK](https://github.com/zendesk/commonui_sdk_ios/search?q=SDKConfigurations) doesn't use SDKConfigurations.

2022-10-06 22:28 UTC, yauhenipakala commented on nuget/Softeq.ZendeskMessagingSDK.iOS.nuspec
> +                <dependency id="Softeq.ZendeskSDKConfigurationsSDK.iOS" version="1.1.11.4" />
This package has only 2 dependencies: https://github.com/zendesk/messaging_sdk_ios/blob/1a1645c33a00c0705cbe95d536de1b1846e4dcef/ZendeskMessagingSDK.podspec#L25-L26
As you can see ZendeskSDKConfigurationsSDK package will be added based with ZendeskMessagingAPISDK

2022-10-06 22:28 UTC, yauhenipakala commented on nuget/Softeq.ZendeskSupportSDK.iOS.nuspec
> +                <dependency id="Softeq.ZendeskCoreSDK.iOS" version="2.7.0.4" />
Looks like this package has only 2 dependencies: https://github.com/zendesk/support_sdk_ios/blob/da1a8684a413206f24ebddfed35fe2499e96fdfd/ZendeskSupportSDK.podspec#L25-L26

2022-10-06 22:28 UTC, yauhenipakala commented on SupportSDK.Bindings/SupportSDK.Bindings.csproj
>      <NativeReference Include="..\CommonUISDK.Bindings\CommonUISDK.framework">
Just a comment: CommonUISDK.Bindings project is not required

2022-10-06 23:30 UTC, wcoder approved these changes

2022-10-11 21:20 UTC, merged

2022-10-12 12:25 UTC, yauhenipakala commented
@thisisthekap Thanks for the contribution! 🚀
New packages are available in NuGet:
https://www.nuget.org/packages?q=Tags%3A%22zendesk%22%2C%22ios%22%2C%22softeq%22

2022-10-12 12:27 UTC, wcoder commented on nuget/Softeq.ZendeskCommonUISDK.iOS.nuspec
> +                <dependency id="Softeq.ZendeskSDKConfigurationsSDK.iOS" version="1.1.11.4" />
Fixed in #11

2022-10-12 12:27 UTC, wcoder commented on nuget/Softeq.ZendeskMessagingSDK.iOS.nuspec
> +                <dependency id="Softeq.ZendeskSDKConfigurationsSDK.iOS" version="1.1.11.4" />
Fixed in #11

2022-10-12 12:27 UTC, wcoder commented on nuget/Softeq.ZendeskSupportSDK.iOS.nuspec
> +                <dependency id="Softeq.ZendeskCoreSDK.iOS" version="2.7.0.4" />
Fixed in #11